export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

export const PRODUCT_CREATE = 'PRODUCT_CREATE'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
export const PRODUCT_SAVE_FAILURE = 'PRODUCT_SAVE_FAILURE'

export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'